# Generated by Django 2.2 on 2020-07-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Categoria_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(max_length=50)),
                ('Numero', models.IntegerField()),
                ('Comuna', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Producto_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Venta_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Monto_Final', models.IntegerField()),
                ('Descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Provedor_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('WEB', models.CharField(max_length=50)),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Cliente_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super.Direccion')),
            ],
        ),
    ]
