# Generated by Django 2.2 on 2020-07-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Super', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Descripcion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Venta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Super.Venta'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='Producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Super.Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Super.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Super.Proveedor'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Detalle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Super.Detalle'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
