# Generated by Django 2.2 on 2020-07-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Super', '0002_auto_20200701_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Direccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Venta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Venta'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='Producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Proveedor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Detalle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Detalle'),
        ),
    ]
