# Generated by Django 2.2 on 2020-07-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super', '0003_auto_20200701_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Provedores'},
        ),
    ]
