# Generated by Django 2.2 on 2020-07-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Super', '0004_auto_20200701_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='Provedor_Id',
            new_name='Proveedor_Id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Super.Proveedor', to_field='Provedor_Id'),
        ),
    ]
